### ISSUE TITLE
支持语音指令

### ISSUE THREAD

**Issue by winter60** [H1DDENADM1N/CapsWriter-Offline#10]
大佬有没有兴趣做一下这个功能？在手机上我们经常让自己的语音小助手执行指令，我在想，电脑上是不是也可以？  
 我喜欢用 Windows 上的 quicker, 想要实现语音指令执行 quicker 上的动作。

 以下是功能：
1. 可以配置语音指令关键词，  以及对应单独运行的命令。 如：
```
打开资料:file:///d:\我的资料\
关机:shutdown -s -t 5

```

2. 支持配置全局语音指令的运行命令，所有的配置好的语音指令关键词都会去调用该命令 。 可以传入关键字参数,`$1`代表指令关键词。如：url://xxxxx?$1 。  主要是第1点太麻烦，想统一用quicker处理。
```
quicker:runaction:8ee2466c-2e47-447b-971b-eed4f8e2542c?keyword=$1
```

3. 为了避免和输入文字冲突。 可以按下某个键触发，比如说 control / alt + capslock，或者其他的。(  又或者什么都不用改， 执行语音 指令的时候，不要有输入焦点就行   )

你觉得该功能可以的话，可以讨论一下

**Comment by H1DDENADM1N** [comment]
不会考虑加入语音助手类功能，简单的操作，动嘴说话控制电脑还没有键鼠操作快；复杂的操作，不如直接用脚本。

**Comment by winter60** [comment]
“简单的操作，动嘴说话控制电脑还没有键鼠操作快” ，  这句话说的对。
“复杂的操作，不如直接用脚本”  ，这句话说的也对， 但是脚本的触发方式同样得键盘、和鼠标 ，这里只是增加一种触发方式 。我目前触发动作的方式有太多了， 在 quicker 里面 就有悬浮面板、仪表盘、轮盘、左键辅助、高级鼠标触发、鼠标手势， 快捷键、扩展热键、文本指令、事件触发等，  差不多也有上百种操作了 。 

而语音来触发动作，实现了在几乎不动手的情况下执行动作， 目前我把触发语音按下capslock的方式，用仅长按鼠标某键替代了。 **如果能支持语音指令的功能，那么就能够实现在最少用手的情况下，不需要记忆任何触发方式， 可以实现无数种方式指令。 如果说用快捷键的话， 那么20种指令就要记20个快捷键。**
