### ISSUE TITLE
翻译功能无法使用

### ISSUE THREAD

**Issue by Max66888** [H1DDENADM1N/CapsWriter-Offline#11]
在本机电脑启动服务端和客户端后离线翻译和在线翻译均正常

![Snipaste_2024-03-22_14-07-44](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/eb44957e-8189-4d99-82d6-f602bbe6c3f0)

但服务端在另一台机器启动就只能正常输入，无法使用翻译功能,离线和在线均不行
即Server端和Client端在不同电脑上（同一局域网，均关闭防火墙，端口畅通）

![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/d6e2bd00-74fb-4ae1-8539-721a0b192c70)
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/5260a9f7-5654-4961-9f09-3a53eb62212c)

是不是翻译端口默认给127.0.0.1了

Config文件仅改动了Server地址和目标语言

![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/06c16835-db77-44cd-bfec-f1acafee25a2)

**Comment by H1DDENADM1N** [comment]
离线翻译修复了[fix11](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/89d47b137efb662f707eb876fced8a95f472283b)。在线翻译需要你修改 `config.py` `class DeepLXConfig` 中的 `api = "http://127.0.0.1:1188/translate"`

**Comment by Max66888** [comment]
在线翻译已正常使用，但离线翻译仍然错误
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/cbe9eedd-92d1-489a-85ad-85a9c2681e14)
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/101586089/37f7e2a9-4cc1-450b-8c51-b7f8ec549477)

**Comment by H1DDENADM1N** [comment]
> 在线翻译已正常使用，但离线翻译仍然错误 

这样改下 https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/bc4e8b1dd5f46a6b242562e4849046daf1e058d0
