### ISSUE TITLE
能不能在运行client/server  exe的时候自动结束之前的进程？

### ISSUE THREAD

**Issue by kulkatt** [H1DDENADM1N/CapsWriter-Offline#12]
有时候systray右键退出之后进程并没有结束

![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/24421888/95f269ff-17c0-49a6-a1a7-bc7f147c5624)

**Comment by H1DDENADM1N** [comment]
已加入关闭时结束此程序[fix 12](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/fb8d85b455eae2384bfc1b920e8514f8e226f5bb)
