### ISSUE TITLE
1.2.1版，录音时暂停其他音频设置为False后，仍然会将其他音频静音

### ISSUE THREAD

**Issue by kulkatt** [H1DDENADM1N/CapsWriter-Offline#13]
pause_other_audio = False             # 录音时暂停其他音频播放

1.2.1版
似乎如果设置为True那在按激活键的时候似乎和键盘的play/pause行为相同
设置为false就是纯静音
但是在有多个播放源的时候会造成混乱，比如mpv就不会被暂停，只会被静音

总之有时候还是需要识别PC正在播放的声音的，所以希望加一个完全不做静音的设置值

**Comment by H1DDENADM1N** [comment]
还有个 mute_other_audio = True 参数需要改

**Comment by H1DDENADM1N** [comment]
就在你改的那行的上一行

**Comment by kulkatt** [comment]
> 还有个 mute_other_audio = True 参数需要改

谢谢， 搞定了
