### ISSUE TITLE
这种情况是什么原因呢

### ISSUE THREAD

**Issue by zhouxiansheng** [H1DDENADM1N/CapsWriter-Offline#14]
![微信图片_20240407222906](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/110282156/4ca17220-eec1-4936-85b9-ed7f6434be34)
这种情况是什么原因呢，我重装了系统，目前系统是win10 LTSC 21H2版本，安装了Python 3.12.2 (64-bit)，现在出现这样的情况，无法打开，重新下载最新的版本也无济于事，还是这样的报错，有没有大佬解惑，到底是什么地方出现了问题。

**Comment by H1DDENADM1N** [comment]
大概是被杀毒软件误杀了，建议加白名单重新解压
