### ISSUE TITLE
使用时暂停其他的音频，而不是静音

### ISSUE THREAD

**Issue by QQQOrange** [H1DDENADM1N/CapsWriter-Offline#2]
现在使用的时候，它不是暂停，而是静音

那例如你在看什么视频的时候，突然要回 QQ，然后就语音输入 QQ。

然后等你输完之后发现，视频已经播放了好多

理想情况是输入的，同时其他的所有音频都暂停掉，输入结束后，被暂停的音频自动打开

**Comment by H1DDENADM1N** [comment]
哈哈哈，我也想暂停啊，可是python无法实现控制其他程序暂停音频，只能控制系统静音。
控制其他程序暂停音乐播放需要调用其他程序的API，市面上有那么多的播放器，不是所有的都开放API，开放了，也让一个软件一个软件的适配维护，怕不是要累死。

**Comment by QQQOrange** [comment]
> 哈哈哈，我也想暂停啊，可是python无法实现控制其他程序暂停音频，只能控制系统静音。
> 控制其他程序暂停音乐播放需要调用其他程序的API，市面上有那么多的播放器，不是所有的都开放API，开放了，也让一个软件一个软件的适配维护，怕不是要累死。

有道理呀，静音也挺好的，好用，哈哈

**Comment by H1DDENADM1N** [comment]
已成功实现 [新增功能 支持 录音时暂停其他音频播放 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/228d79a208a051b5b1ef0d3396072f02182488ca)

效果图：
![暂停播放](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/0c97be57-c4cc-4a06-b675-e1e7e4669944)

**Comment by QQQOrange** [comment]
> 已成功实现 [新增功能 支持 录音时暂停其他音频播放 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/228d79a208a051b5b1ef0d3396072f02182488ca)
> 
> 效果图： ![暂停播放](https://private-user-images.githubusercontent.com/65646535/307656376-0c97be57-c4cc-4a06-b675-e1e7e4669944.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjI1MTgsIm5iZiI6MTcwODkyMjIxOCwicGF0aCI6Ii82NTY0NjUzNS8zMDc2NTYzNzYtMGM5N2JlNTctYzRjYy00YTA2LWI2NzUtZTFlN2U0NjY5OTQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDRhMmE5ZDAyZTVlODAyYjgxM2M2NDE4MjNhNDg3OTI4ZDU4ZTcwOTNkZTFjMzMxNDViZjM0MmIwZmYzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcWS3idF9gtfc6q5SpEcKHVit9fryoe-ABKLIKiP41s) [ ![暂停播放](https://private-user-images.githubusercontent.com/65646535/307656376-0c97be57-c4cc-4a06-b675-e1e7e4669944.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjI1MTgsIm5iZiI6MTcwODkyMjIxOCwicGF0aCI6Ii82NTY0NjUzNS8zMDc2NTYzNzYtMGM5N2JlNTctYzRjYy00YTA2LWI2NzUtZTFlN2U0NjY5OTQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDRhMmE5ZDAyZTVlODAyYjgxM2M2NDE4MjNhNDg3OTI4ZDU4ZTcwOTNkZTFjMzMxNDViZjM0MmIwZmYzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcWS3idF9gtfc6q5SpEcKHVit9fryoe-ABKLIKiP41s) ](https://private-user-images.githubusercontent.com/65646535/307656376-0c97be57-c4cc-4a06-b675-e1e7e4669944.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjI1MTgsIm5iZiI6MTcwODkyMjIxOCwicGF0aCI6Ii82NTY0NjUzNS8zMDc2NTYzNzYtMGM5N2JlNTctYzRjYy00YTA2LWI2NzUtZTFlN2U0NjY5OTQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDRhMmE5ZDAyZTVlODAyYjgxM2M2NDE4MjNhNDg3OTI4ZDU4ZTcwOTNkZTFjMzMxNDViZjM0MmIwZmYzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcWS3idF9gtfc6q5SpEcKHVit9fryoe-ABKLIKiP41s) [ ](https://private-user-images.githubusercontent.com/65646535/307656376-0c97be57-c4cc-4a06-b675-e1e7e4669944.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjI1MTgsIm5iZiI6MTcwODkyMjIxOCwicGF0aCI6Ii82NTY0NjUzNS8zMDc2NTYzNzYtMGM5N2JlNTctYzRjYy00YTA2LWI2NzUtZTFlN2U0NjY5OTQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA0MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDRhMmE5ZDAyZTVlODAyYjgxM2M2NDE4MjNhNDg3OTI4ZDU4ZTcwOTNkZTFjMzMxNDViZjM0MmIwZmYzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcWS3idF9gtfc6q5SpEcKHVit9fryoe-ABKLIKiP41s)

牛逼呀，老哥
