### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by qhgy** [H1DDENADM1N/CapsWriter-Offline#21]
hot-rules加了这个
回车      =       \r\n
换行      =       \r\n

原版里面可以执行回车、换行的指令
这个修改版没反应

另外说回车换行 会有错误提示：
[WinError 123] 文件名、目录名或卷标语法不正确。: '2024\\05\\assets\\(20240510-095332)gd7jq0il.mp3' -> '2024\\05\\assets\\(20240510-095332)\r\n.mp3'

这个原版也有

**Comment by H1DDENADM1N** [comment]
参考 https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/6d21db8d024757ddb780f541fd7dba66a4b91a90#diff-c5208f0df37da9787d52455d4b59ff478bbf6a687f119130bbabe5cf1e99ce3bR26 

加一句 `file_stem = re.sub(r"\r\n", " ", file_stem)`

就可以了

**Comment by qhgy** [comment]
感谢！
大佬有空可否把模型更新下
https://github.com/HaujetZhao/CapsWriter-Offline/issues/120

**Comment by H1DDENADM1N** [comment]
> 感谢！
> 
> 大佬有空可否把模型更新下
> 
> https://github.com/HaujetZhao/CapsWriter-Offline/issues/120
> 
> 
> 
> 

已有现成可用的

https://huggingface.co/yiyu-earth/sherpa-onnx-paraformer-zh-2024-04-25/

**Comment by H1DDENADM1N** [comment]
> 感谢！ 大佬有空可否把模型更新下 [HaujetZhao#120](https://github.com/HaujetZhao/CapsWriter-Offline/issues/120)

我发布了更新 https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v1.2.2

**Comment by qhgy** [comment]
> > 感谢！ 大佬有空可否把模型更新下 [HaujetZhao#120](https://github.com/HaujetZhao/CapsWriter-Offline/issues/120)
> 
> 我发布了更新 https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v1.2.2

666
