### ISSUE TITLE
增加选择设备的功能

### ISSUE THREAD

**Issue by Xiemarc** [H1DDENADM1N/CapsWriter-Offline#22]
期望能够增加选择输入/输出设备的功能，输入设备就是目前的功能。但是开远程会议的时候，有时候也是想要将对面的语音转为语音的，能否将这个功能也实现。谢啦

**Comment by ffgg536956** [comment]
支持，我也有类似的需求，有时候想将b站里面正在播放的声音，实时语音识别成文稿，方便自己整理笔记。这时，如果程序支持将监听的设备改为系统内置声卡，而不是麦克风，那肯定会大大提高音频的识别的质量。
