### ISSUE TITLE
客户端界面无法通过，任务栏的show菜单显示出来。

### ISSUE THREAD

**Issue by ffgg536956** [H1DDENADM1N/CapsWriter-Offline#23]
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/133084034/165049ea-4724-4aa3-8adc-82c2f8c13cb0)

![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/133084034/5d84da88-6796-492d-835b-22513e6341e9)

      让我感觉到非常疑惑的是，明明软件可以正常的语音识别转文字，但是客户端在首仅仅在首次打开时才有界面，后续在托盘区始终无法显示其界面， 只能让服务端的界面 正常显示出 来，重启软件依然未能解决。难道客户端本来就是 仅在首次打开的时候短暂显示一下吗？
    start_server_gui.exe  与 start_client_gui_admin.exe   这两个软件我都有尝试点击，但问题均未解决。

**Comment by H1DDENADM1N** [comment]
我这里测试的是可以正常唤起主界面的呢。
鼠标在屏幕左右边缘晃晃，看看是不是贴边隐藏了。另，还可以通过鼠标左键双击托盘图标显示窗口。

**Comment by H1DDENADM1N** [comment]
还可以通过双击托盘图标显示窗口

**Comment by H1DDENADM1N** [comment]
哦对了，除了贴边隐藏了，还有一种可能，看下是不是被电脑管家类程序给当弹窗广告拦截了。
