### ISSUE TITLE
最新版本 这个窗口不会自动隐藏到托盘

### ISSUE THREAD

**Issue by QQQOrange** [H1DDENADM1N/CapsWriter-Offline#24]
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/62794181/d101fc3e-2d0c-4060-9816-d554c77c6166)

**Comment by H1DDENADM1N** [comment]
修改 config.py ClientConfig 中的 shrink_automatically_to_tray

**Comment by QQQOrange** [comment]
> 修改 config.py ClientConfig 中的 shrink_automatically_to_tray

ok k 已经搞定了，又发现一个新的问题，如果不把麦克风常开着的话，就是在 config.py 里面把麦克风常开的话，那么每次按下快捷键输出来的话，总会掉几个字，而且还是句首的几个字

**Comment by H1DDENADM1N** [comment]
因为启动麦克风需要时间。可以按下按键后等个半秒再说话

**Comment by QQQOrange** [comment]
> 因为启动麦克风需要时间。可以按下按键后等个半秒再说话

好吧，谢谢老哥
