### ISSUE TITLE
求离线翻译功能，真的非常非常需要

### ISSUE THREAD

**Issue by ifkd111** [H1DDENADM1N/CapsWriter-Offline#26]
实在非常需要这个功能，求求了

**Comment by H1DDENADM1N** [comment]
这是已有功能啊

按下键盘上的 Left Shift 再按 CapsLock 可以将识别结果[离线翻译](https://huggingface.co/Helsinki-NLP/opus-mt-zh-en)为英文，并将识别结果立刻输入

按下键盘上的 Ctrl + Alt + P ，可以将光标选中的 中文 [离线翻译](https://huggingface.co/Helsinki-NLP/opus-mt-zh-en)为 英文 ，并自动覆盖替换原文
