### ISSUE TITLE
运行提示找不到文件

### ISSUE THREAD

**Issue by hwp460170747** [H1DDENADM1N/CapsWriter-Offline#29]
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/67583341/0d29435a-ddf9-461a-b1cf-1d25948c1d69)
运行“start_server_gui.exe”提示系统找不到指定的文件是怎么办

**Comment by H1DDENADM1N** [comment]
检查下默认麦克风设置的是什么

**Comment by H1DDENADM1N** [comment]
> [❗ 注意事项 1. 存在杀毒误报，建议关闭杀毒软件和防火墙，再解压](https://github.com/H1DDENADM1N/CapsWriter-Offline#-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by H1DDENADM1N** [comment]
在另一台 win 11 LTSC 的电脑遇到了同样的问题，修复参考：[使用tasklist取代wmic（win11LTSC已移除wmic）](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/320edb6c0683bf4fbaac3d568bec65bb5bfcbb7e)https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/320edb6c0683bf4fbaac3d568bec65bb5bfcbb7e
