### ISSUE TITLE
在属性里设为以管理员方式启动后，无法以快捷方式的方式开机自启

### ISSUE THREAD

**Issue by QQQOrange** [H1DDENADM1N/CapsWriter-Offline#3]
简单说，就是在属性里面设置为以管理员方式启动之后，把快捷方式放到 startup 文件夹里

但是重启后，它并不会启动

最好是软件默认提供一个开机自启的选项

**Comment by H1DDENADM1N** [comment]
如果你需要管理员权限启动，请使用**加入了自动UAC提权的Pystand**（来自我的Pystand分支 [releases](https://github.com/H1DDENADM1N/PyStand/releases)）：[start_client_gui.zip](https://github.com/H1DDENADM1N/CapsWriter-Offline/files/14398835/start_client_gui.zip) 替换原文件，然后再创建快捷方式。修改无自动 uac 提权的Pystand的属性是不会有效果的。

**Comment by QQQOrange** [comment]
> 如果你需要管理员权限启动，请使用**加入了自动UAC提权的Pystand**（来自我的Pystand分支 [releases](https://github.com/H1DDENADM1N/PyStand/releases)）：[start_client_gui.zip](https://github.com/H1DDENADM1N/CapsWriter-Offline/files/14398835/start_client_gui.zip) 替换原文件，然后再创建快捷方式。修改无自动 uac 提权的Pystand的属性是不会有效果的。

好嘞 谢谢老哥

**Comment by H1DDENADM1N** [comment]
[Pystand自动UAC提权原理](https://github.com/H1DDENADM1N/PyStand/commit/8be144dfa1ef2d145a96b95d8d162498a6f785b0)

**Comment by QQQOrange** [comment]
> [Pystand自动UAC提权原理](https://github.com/H1DDENADM1N/PyStand/commit/8be144dfa1ef2d145a96b95d8d162498a6f785b0)

老哥以后每次下载新版之后，都需要自己替换一下吗

**Comment by H1DDENADM1N** [comment]
> > [Pystand自动UAC提权原理](https://github.com/H1DDENADM1N/PyStand/commit/8be144dfa1ef2d145a96b95d8d162498a6f785b0)
> 
> 
> 
> 老哥以后每次下载新版之后，都需要自己替换一下吗

是的

**Comment by QQQOrange** [comment]
> > > [Pystand自动UAC提权原理](https://github.com/H1DDENADM1N/PyStand/commit/8be144dfa1ef2d145a96b95d8d162498a6f785b0)
> > 
> > 
> > 老哥以后每次下载新版之后，都需要自己替换一下吗
> 
> 是的

好的好的

**Comment by H1DDENADM1N** [comment]
@QQQOrange  我发布了更新 [新增功能 支持 以管理员身份启动客户端 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/72dd9cb686f7965eca0e232484956cc63902b5d5) 和 [新增功能 一键以管理员权限启动 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/7399550556cb4704534469e1ed0dc2b1def9bdb9)

以后你希望开机自启动时与管理员权限运行客户端，创建 `start_client_gui_admin.exe` 的快捷方式即可，不要创建 `start_client_gui.exe` 的快捷方式了

**Comment by QQQOrange** [comment]
> @QQQOrange 我发布了更新 [新增功能 支持 以管理员身份启动客户端 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/72dd9cb686f7965eca0e232484956cc63902b5d5) 和 [新增功能 一键以管理员权限启动 ](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/7399550556cb4704534469e1ed0dc2b1def9bdb9)
> 
> 以后你希望开机自启动时与管理员权限运行客户端，创建 `start_client_gui_admin.exe` 的快捷方式即可，不要创建 `start_client_gui.exe` 的快捷方式了

给老哥跪了，牛逼!!!!!
