### ISSUE TITLE
求高亮关键词功能

### ISSUE THREAD

**Issue by ifkd111** [H1DDENADM1N/CapsWriter-Offline#30]
转录长文本后，文本中如果有关键词，能显示红色，比如“重点”、“关注”，等关键词，希望能在转录完成的文本中高亮显示，不一样颜色，或者词前有个标记什么的，只要有标识就行，可以吗？非常需要

**Comment by H1DDENADM1N** [comment]
我发布了一个新项目 [Highlight-Keywords](https://github.com/H1DDENADM1N/Highlight-Keywords) 解决你的需求

![demo](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/8515cce6-af2b-4200-900b-06f1cdc6e887)

**Comment by ifkd111** [comment]
> 我发布了一个新项目 [Highlight-Keywords](https://github.com/H1DDENADM1N/Highlight-Keywords) 解决你的需求
> 
> ![demo](https://private-user-images.githubusercontent.com/65646535/346390511-8515cce6-af2b-4200-900b-06f1cdc6e887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQxMDcsIm5iZiI6MTcyMDQ5MzgwNywicGF0aCI6Ii82NTY0NjUzNS8zNDYzOTA1MTEtODUxNWNjZTYtYWYyYi00MjAwLTkwMGItMDZmMWNkYzZlODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAyNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDM0N2IxNmM5NThjNzQ5MDc3OTc5ODE2N2YwM2Q3MjhhYTk1MWU3Y2E4YTIzNWQ4YmI1ZDlhZGVkODJhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_rtXL31eehfaIZodOE6k04WFxMP4QiyD_ajg0fVczM)
义父，怎么镶嵌到这个项目里去呢？CapsWriter-Offline这个东西里怎么用呢？

**Comment by ifkd111** [comment]
> 我发布了一个新项目 [Highlight-Keywords](https://github.com/H1DDENADM1N/Highlight-Keywords) 解决你的需求
> 
> ![demo](https://private-user-images.githubusercontent.com/65646535/346390511-8515cce6-af2b-4200-900b-06f1cdc6e887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQ3MTQsIm5iZiI6MTcyMDQ5NDQxNCwicGF0aCI6Ii82NTY0NjUzNS8zNDYzOTA1MTEtODUxNWNjZTYtYWYyYi00MjAwLTkwMGItMDZmMWNkYzZlODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAzMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNjM5Y2Q4Zjk4OTg4NDBkM2Y4ZTE2MmFlNGIwYTQyNzYxMDQ5Y2E4Yjc1NmRjMGNlMGYzYzM0NjM5ZWJlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c15Wb-mgo8YxqyMmwwydgwVSbZkpe6ZJbnbaQ2qAW2g)
亲，怎么联系你？我看了你几个东西，都非常需要，想继续探讨下~
qq326567877@gmail.com
我邮箱，求联系方式，非常需要，谢谢大佬

**Comment by ifkd111** [comment]
> 我发布了一个新项目 [Highlight-Keywords](https://github.com/H1DDENADM1N/Highlight-Keywords) 解决你的需求
> 
> ![demo](https://private-user-images.githubusercontent.com/65646535/346390511-8515cce6-af2b-4200-900b-06f1cdc6e887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQ3MTQsIm5iZiI6MTcyMDQ5NDQxNCwicGF0aCI6Ii82NTY0NjUzNS8zNDYzOTA1MTEtODUxNWNjZTYtYWYyYi00MjAwLTkwMGItMDZmMWNkYzZlODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAzMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNjM5Y2Q4Zjk4OTg4NDBkM2Y4ZTE2MmFlNGIwYTQyNzYxMDQ5Y2E4Yjc1NmRjMGNlMGYzYzM0NjM5ZWJlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c15Wb-mgo8YxqyMmwwydgwVSbZkpe6ZJbnbaQ2qAW2g)

亲，怎么联系你？我看了你几个东西，都非常需要，想继续探讨下~
qq326567877@gmail.com
我邮箱，求联系方式，非常需要，谢谢大佬

**Comment by ifkd111** [comment]
13818793977，求回复，谢谢~+v，非常需要


H1DDENADM1N ***@***.***> 于2024年7月7日周日 00:21写道：

**Comment by ifkd111** [comment]
还有就是，这个怎么用呢？把代码整合到 CapsWriter-Offline？


H1DDENADM1N ***@***.***> 于2024年7月7日周日 00:21写道：

**Comment by H1DDENADM1N** [comment]
在这里下载预发布版本试用：https://github.com/H1DDENADM1N/Highlight-Keywords/releases/tag/v0.1.0

**Comment by H1DDENADM1N** [comment]
首个正式版已发布，快了更新吧：https://github.com/H1DDENADM1N/Highlight-Keywords/releases

- 新增可选择多个文件
- 新增 icon
- 更美观的暗色半透明界面
- 移除 cli

![demo](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/f4239bca-0aaa-42c6-8709-393c90f69919)

**Comment by ifkd111** [comment]
CapsWriter-Offline，怎么把这个整合进去呢？大佬

**Comment by H1DDENADM1N** [comment]
>  CapsWriter-Offline，怎么把这个整合进去呢？大佬

这是另一个独立项目，并不会考虑继续往CapsWriter里塞东西了，它已经太臃肿了。

**Comment by ifkd111** [comment]
> > CapsWriter-Offline，怎么把这个整合进去呢？大佬
> 
> 这是另一个独立项目，并不会考虑继续往CapsWriter里塞东西了，它已经太臃肿了。

感谢大佬，我现在工作需要，capswriter其实非常好用，录音转文字或者实时转文字，甚至tmspeech这些项目，希望有整合的文字高亮。
再次感谢大佬，回复速度真的快

**Comment by H1DDENADM1N** [comment]
### v0.3.0 版本以发布： 

https://github.com/H1DDENADM1N/Highlight-Keywords/releases

- 可选添加系统级右键菜单（在 `.txt`、`.md`、`.ocr` 单个文件上鼠标右击，快速打开 `highlight_keywords.exe`）
- 可拖动多个文件到``highlight_keywords.exe``上，批量选择多个文件

快来更新体验吧

**Comment by ifkd111** [comment]
13818793977
加V，急求
capswriter-offline有API吗？


H1DDENADM1N ***@***.***> 于2024年7月11日周四 10:36写道：
