### ISSUE TITLE
是否可以给翻译功能增加开关？

### ISSUE THREAD

**Issue by seeingrain** [H1DDENADM1N/CapsWriter-Offline#32]
首先，感谢大佬的辛勤付出。

我觉得这个分支有两个比较优秀的特性：
1. 进行语音输入的时候会有提示（Hint）。
2. 可以自动隐藏到托盘中去，不用看丑陋的任务栏，但是想看日志的时候，又可以在托盘里面看到日志。

但是我不需要它的翻译功能，看起来好像翻译的模型也占了挺大内存。能不能有一个开关来设置关闭掉，不需要的翻译功能，以节省内存？

**Comment by seeingrain** [comment]
其实对我来说，我只需要一个长按 caps 按钮进行语音输入的功能就够了。嘿嘿。

**Comment by H1DDENADM1N** [comment]
[v1.0.3](https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v1.0.3) 版本不包含翻译，可以看看是否你的符合需求

**Comment by seeingrain** [comment]
> [v1.0.3](https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v1.0.3) 版本不包含翻译，可以看看是否你的符合需求

嗯嗯，多谢啦~~~

**Comment by H1DDENADM1N** [comment]
新版已增加不启用翻译功能的设置项
