### ISSUE TITLE
请求支持更快更准的新模型：sensevoice

### ISSUE THREAD

**Issue by photkey** [H1DDENADM1N/CapsWriter-Offline#33]
[Sensevoice 中文readme](https://github.com/FunAudioLLM/SenseVoice/blob/main/README_zh.md)

![image](https://github.com/user-attachments/assets/358640ff-1c3a-429e-9990-c36daa36ea18)
更快更准，支持：zh/yue/en/ja/ko，在音频时长增加的情况下，推理耗时无明显增加，这点挺好的。
希望能够支持这个模型。

**Comment by mofanx** [comment]
确实可以支持sensevoice模型了，推荐大佬更新下！下面说下我的修改方法：
一、下载模型，并解压到capswriter 的models文件夹下。

参考网址：https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html#sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17

wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2

tar xvf sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
rm sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2

二、修改config.py文件
```
class ModelPaths:
    model_dir = Path() / 'models'
    paraformer_path = Path() / 'models' / 'sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17' / 'model.int8.onnx'   # 语音模型
    tokens_path = Path() / 'models' / 'sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17' / 'tokens.txt'
    # punc_model_dir = Path() / 'models' / 'punc_ct-transformer_cn-en'    # 标点模型
    opus_mt_dir = Path() / 'models' / 'Helsinki-NLP--opus-mt-zh-en'     # 离线翻译模型


class ParaformerArgs:
    model = f'{ModelPaths.paraformer_path}'
    tokens = f'{ModelPaths.tokens_path}'
    num_threads = 6
    sample_rate = 16000
    # feature_dim = 80
    # decoding_method = 'greedy_search'
    use_itn = True
    language = "auto"
    debug = False
    provider = "cpu"

```


三、修改server_init_recognizer.py文件

```
def init_recognizer(queue_in: Queue, queue_out: Queue, sockets_id):

    # Ctrl-C 退出
    signal.signal(signal.SIGINT, lambda signum, frame: exit())

    # 导入模块
    with console.status("载入模块中…", spinner="bouncingBall", spinner_style="yellow"):
        import sherpa_onnx

    console.print('[green4]模块加载完成', end='\n\n')

    # 载入语音模型
    console.print('[yellow]语音模型载入中，载入时长约 20 秒，请耐心等待...', end='\r'); t1 = time.time()
    recognizer = sherpa_onnx.OfflineRecognizer.from_sense_voice(
        **{key: value for key, value in ParaformerArgs.__dict__.items() if not key.startswith('_')}
    )
    console.print(f'[green4]语音模型载入完成', end='\n\n')



    # 清空物理内存工作集
    if system() == 'Windows':
        empty_current_working_set()

    queue_out.put(True)  # 通知主进程加载完了

    while True:
        # 从队列中获取任务消息
        # 阻塞最多1秒，便于中断退出
        try:
            task = queue_in.get(timeout=1)       
        except:
            continue

        if task.socket_id not in sockets_id:    # 检查任务所属的连接是否存活
            continue
```

四、修改server_recognize.py文件，去掉punc_model相关的代码：

```
import re
import time

import numpy as np 

from util.server_cosmic import console
from config import ServerConfig as Config
from util.server_classes import Task, Result
from util.chinese_itn import chinese_to_num
from util.format_tools import adjust_space
from rich import inspect


results = {}


def format_text(text):
    if Config.format_spell:
        text = adjust_space(text)       # 调空格
    if Config.format_num:
        text = chinese_to_num(text)     # 转数字
    if Config.format_spell:
        text = adjust_space(text)       # 调空格
    return text


def recognize(recognizer, task: Task):

    # inspect({key:value for key, value in task.__dict__.items() if not key.startswith('_') and key != 'data'})
    # todo 清空遗存的任务结果

    # 确保结果容器存在
    if task.task_id not in results:
        results[task.task_id] = Result(task.task_id, task.socket_id, task.source)

    # 取出结果容器
    result = results[task.task_id]

    # 片段预处理
    samples = np.frombuffer(task.data, dtype=np.float32)
    duration = len(samples) / task.samplerate
    result.duration += duration - task.overlap
    if task.is_final:
        result.duration += task.overlap

    # 识别片段
    stream = recognizer.create_stream()
    stream.accept_waveform(task.samplerate, samples)
    recognizer.decode_stream(stream)

    # 记录识别时间
    result.time_start = task.time_start
    result.time_submit = task.time_submit
    result.time_complete = time.time()

    # 先粗去重，依据：字级时间戳
    m = n = len(stream.result.timestamps)
    for i, timestamp in enumerate(stream.result.timestamps, start=0):
        if timestamp > task.overlap / 2: 
            m = i
            break
    for i, timestamp in enumerate(stream.result.timestamps, start=1):
        n = i
        if timestamp > duration - task.overlap / 2:
            break
    if not result.timestamps:
        m = 0
    if task.is_final:
        n = len(stream.result.timestamps)

    # 再细去重，依据：在端点是否有重复的字
    if result.tokens and result.tokens[-2:] == stream.result.tokens[m:n][:2]:
        m += 2
    elif result.tokens and result.tokens[-1:] == stream.result.tokens[m:n][:1]:
        m += 1

    # 最后与先前的结果合并
    result.timestamps += [t + task.offset for t in stream.result.timestamps[m:n]]
    result.tokens += [token for token in stream.result.tokens[m:n]]

    # token 合并为文本
    text = ' '.join(result.tokens).replace('@@ ', '')
    text = re.sub('([^a-zA-Z0-9]) (?![a-zA-Z0-9])', r'\1', text)

    result.text = text

    if not task.is_final:
        return result

    # 调整文本格式
    result.text = format_text(text)

    # 若最后一个片段完成识别，从字典摘取任务
    result = results.pop(task.task_id)
    result.is_final = True

    return result

```

五、修改项目site-packages下和sherpa_onnx相关的文件（原因是自带的版本不支持sensevoice）。
我是在虚拟环境中，使用pip install sherpa_onnx，重新安装了一个版本，然后再复制系统site-packages下的sherpa_onnx文件夹和_sherpa_onnx.cp311-win_amd64.pyd，到capswriter 的site-packages文件夹下。

六、运行
.\runtime\python.exe  .\core_server.py


 大功告成！
 
 @H1DDENADM1N 希望大佬可以更新下源码！让大家愉快玩耍！

**Comment by photkey** [comment]
@mofanx 
大佬，使用sensevoice 速度和准确率有明显提升吗？

**Comment by H1DDENADM1N** [comment]
@mofanx 感谢大佬的方法，成功换到了sensevoice模型，我发布了新的1.3.1版本，欢迎测试尝鲜。

123盘 https://www.123pan.com/s/qBxUVv-H4Zq3.html 提取码:h8vb

**Comment by photkey** [comment]
> @mofanx 感谢大佬的方法，成功换到了sensevoice模型，我发布了新的1.3.1版本，欢迎测试尝鲜。
> 
> 123盘 https://www.123pan.com/s/qBxUVv-H4Zq3.html 提取码:h8vb

@H1DDENADM1N  123网盘 现在不是会员好像下不了超过1G的文件？ 不登录 下载需要收费0.5元；登录下载 需要办会员……，所以能否提供一下阿里云盘的下载地址？

**Comment by H1DDENADM1N** [comment]
@photkey 阿里云盘只能快传无法分享，速下 https://www.alipan.com/t/whyXHeA1P9mxH6AebXEx

百度盘 https://pan.baidu.com/s/1shw8Cp1fE-RT8QvOPBb29g?pwd=s282 提取码: s282

![图片](https://github.com/user-attachments/assets/48862514-a854-469d-aea7-c9b0a11dc0db)

**Comment by photkey** [comment]
@H1DDENADM1N  谢谢，百度网盘慢慢下吧

**Comment by Xiemarc** [comment]
> @photkey 阿里云盘只能快传无法分享，速下 https://www.alipan.com/t/whyXHeA1P9mxH6AebXEx
> 
> 百度盘 https://pan.baidu.com/s/1shw8Cp1fE-RT8QvOPBb29g?pwd=s282 提取码: s282
> 
> ![图片](https://private-user-images.githubusercontent.com/65646535/380469595-48862514-a854-469d-aea7-c9b0a11dc0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzkzMzYsIm5iZiI6MTczMDA3OTAzNiwicGF0aCI6Ii82NTY0NjUzNS8zODA0Njk1OTUtNDg4NjI1MTQtYTg1NC00NjlkLWFlYTctYzliMGExMWRjMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAxMzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MTdjZDdjZDg5NjZlNWFkNTNmZjU5ZGI3Y2EzZjUyMzg4YTljNTFlYTI4NGY3Y2E1ZmJhODQ0YmEwNjU3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fy_7lRLCNQdOoeeW8RCb_ncINm3tasrltJh4PN_dEHg)

@H1DDENADM1N 麻烦问下，下载这个直接替换，还是要完成上面各个py文件内部代码的调整

**Comment by H1DDENADM1N** [comment]
> @H1DDENADM1N 麻烦问下，下载这个直接替换，还是要完成上面各个py文件内部代码的调整

先删除原来的版本，再解压新版。

**Comment by mofanx** [comment]
> @mofanx 感谢大佬的方法，成功换到了sensevoice模型，我发布了新的1.3.1版本，欢迎测试尝鲜。
> 
> 123盘 https://www.123pan.com/s/qBxUVv-H4Zq3.html 提取码:h8vb

@H1DDENADM1N 大佬速度真快，本来还在为怎么告知你发愁了，没想到这么快就更新好了👍👍👍 
另外，大家如果123盘下载受限的话，可以试试装个123云盘下载辅助的油猴脚本😁

**Comment by Xiemarc** [comment]
@H1DDENADM1N 大佬，能否在隔壁项目中，更新下模型文件，可以直接使用的，谢谢啦

**Comment by H1DDENADM1N** [comment]
> @H1DDENADM1N 大佬，能否在隔壁项目中，更新下模型文件，可以直接使用的，谢谢啦

@mofanx 写的方法很完整，你可以自己改改试下。我知道目前我这个分支已经太肿太吃内存了,但我又懒得再改原版了，毕竟能用就行，原版funasr模型并不差，sensevoice模型也没感觉有特别大提升，反而说快了丢标点符号。

**Comment by rzrhu** [comment]
> 确实可以支持sensevoice模型了，推荐大佬更新下！下面说下我的修改方法： 一、下载模型，并解压到capswriter 的models文件夹下。
> 
> 参考网址：https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html#sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17
> 
> wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
> 
> tar xvf sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2 rm sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
> 
> 二、修改config.py文件
> 
> ```
> class ModelPaths:
>     model_dir = Path() / 'models'
>     paraformer_path = Path() / 'models' / 'sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17' / 'model.int8.onnx'   # 语音模型
>     tokens_path = Path() / 'models' / 'sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17' / 'tokens.txt'
>     # punc_model_dir = Path() / 'models' / 'punc_ct-transformer_cn-en'    # 标点模型
>     opus_mt_dir = Path() / 'models' / 'Helsinki-NLP--opus-mt-zh-en'     # 离线翻译模型
> 
> 
> class ParaformerArgs:
>     model = f'{ModelPaths.paraformer_path}'
>     tokens = f'{ModelPaths.tokens_path}'
>     num_threads = 6
>     sample_rate = 16000
>     # feature_dim = 80
>     # decoding_method = 'greedy_search'
>     use_itn = True
>     language = "auto"
>     debug = False
>     provider = "cpu"
> ```
> 
> 三、修改server_init_recognizer.py文件
> 
> ```
> def init_recognizer(queue_in: Queue, queue_out: Queue, sockets_id):
> 
>     # Ctrl-C 退出
>     signal.signal(signal.SIGINT, lambda signum, frame: exit())
> 
>     # 导入模块
>     with console.status("载入模块中…", spinner="bouncingBall", spinner_style="yellow"):
>         import sherpa_onnx
> 
>     console.print('[green4]模块加载完成', end='\n\n')
> 
>     # 载入语音模型
>     console.print('[yellow]语音模型载入中，载入时长约 20 秒，请耐心等待...', end='\r'); t1 = time.time()
>     recognizer = sherpa_onnx.OfflineRecognizer.from_sense_voice(
>         **{key: value for key, value in ParaformerArgs.__dict__.items() if not key.startswith('_')}
>     )
>     console.print(f'[green4]语音模型载入完成', end='\n\n')
> 
> 
> 
>     # 清空物理内存工作集
>     if system() == 'Windows':
>         empty_current_working_set()
> 
>     queue_out.put(True)  # 通知主进程加载完了
> 
>     while True:
>         # 从队列中获取任务消息
>         # 阻塞最多1秒，便于中断退出
>         try:
>             task = queue_in.get(timeout=1)       
>         except:
>             continue
> 
>         if task.socket_id not in sockets_id:    # 检查任务所属的连接是否存活
>             continue
> ```
> 
> 四、修改server_recognize.py文件，去掉punc_model相关的代码：
> 
> ```
> import re
> import time
> 
> import numpy as np 
> 
> from util.server_cosmic import console
> from config import ServerConfig as Config
> from util.server_classes import Task, Result
> from util.chinese_itn import chinese_to_num
> from util.format_tools import adjust_space
> from rich import inspect
> 
> 
> results = {}
> 
> 
> def format_text(text):
>     if Config.format_spell:
>         text = adjust_space(text)       # 调空格
>     if Config.format_num:
>         text = chinese_to_num(text)     # 转数字
>     if Config.format_spell:
>         text = adjust_space(text)       # 调空格
>     return text
> 
> 
> def recognize(recognizer, task: Task):
> 
>     # inspect({key:value for key, value in task.__dict__.items() if not key.startswith('_') and key != 'data'})
>     # todo 清空遗存的任务结果
> 
>     # 确保结果容器存在
>     if task.task_id not in results:
>         results[task.task_id] = Result(task.task_id, task.socket_id, task.source)
> 
>     # 取出结果容器
>     result = results[task.task_id]
> 
>     # 片段预处理
>     samples = np.frombuffer(task.data, dtype=np.float32)
>     duration = len(samples) / task.samplerate
>     result.duration += duration - task.overlap
>     if task.is_final:
>         result.duration += task.overlap
> 
>     # 识别片段
>     stream = recognizer.create_stream()
>     stream.accept_waveform(task.samplerate, samples)
>     recognizer.decode_stream(stream)
> 
>     # 记录识别时间
>     result.time_start = task.time_start
>     result.time_submit = task.time_submit
>     result.time_complete = time.time()
> 
>     # 先粗去重，依据：字级时间戳
>     m = n = len(stream.result.timestamps)
>     for i, timestamp in enumerate(stream.result.timestamps, start=0):
>         if timestamp > task.overlap / 2: 
>             m = i
>             break
>     for i, timestamp in enumerate(stream.result.timestamps, start=1):
>         n = i
>         if timestamp > duration - task.overlap / 2:
>             break
>     if not result.timestamps:
>         m = 0
>     if task.is_final:
>         n = len(stream.result.timestamps)
> 
>     # 再细去重，依据：在端点是否有重复的字
>     if result.tokens and result.tokens[-2:] == stream.result.tokens[m:n][:2]:
>         m += 2
>     elif result.tokens and result.tokens[-1:] == stream.result.tokens[m:n][:1]:
>         m += 1
> 
>     # 最后与先前的结果合并
>     result.timestamps += [t + task.offset for t in stream.result.timestamps[m:n]]
>     result.tokens += [token for token in stream.result.tokens[m:n]]
> 
>     # token 合并为文本
>     text = ' '.join(result.tokens).replace('@@ ', '')
>     text = re.sub('([^a-zA-Z0-9]) (?![a-zA-Z0-9])', r'\1', text)
> 
>     result.text = text
> 
>     if not task.is_final:
>         return result
> 
>     # 调整文本格式
>     result.text = format_text(text)
> 
>     # 若最后一个片段完成识别，从字典摘取任务
>     result = results.pop(task.task_id)
>     result.is_final = True
> 
>     return result
> ```
> 
> 五、修改项目site-packages下和sherpa_onnx相关的文件（原因是自带的版本不支持sensevoice）。 我是在虚拟环境中，使用pip install sherpa_onnx，重新安装了一个版本，然后再复制系统site-packages下的sherpa_onnx文件夹和_sherpa_onnx.cp311-win_amd64.pyd，到capswriter 的site-packages文件夹下。
> 
> 六、运行 .\runtime\python.exe .\core_server.py
> 
> 大功告成！
> 
> @H1DDENADM1N 希望大佬可以更新下源码！让大家愉快玩耍！

使用了这个方法，语音没有识别出来，空白的，这是为什么
<img width="1150" alt="截屏2024-10-31 下午9 16 07" src="https://github.com/user-attachments/assets/759bce0c-12b9-4536-91d4-c9116c0a3c3e">

**Comment by H1DDENADM1N** [comment]
@rzrhu 检查录音mp3文件是否有人声，检查步骤是否有遗漏。。下载我发布的最新版测试 123盘 https://www.123pan.com/s/qBxUVv-H4Zq3.html 提取码:h8vb

**Comment by rzrhu** [comment]
> @rzrhu 检查录音mp3文件是否有人声，检查步骤是否有遗漏。。下载我发布的最新版测试 123盘 https://www.123pan.com/s/qBxUVv-H4Zq3.html 提取码:h8vb

这里面的一些依赖是不是不支持mac？我下了后，没用起

**Comment by H1DDENADM1N** [comment]
> 这里面的一些依赖是不是不支持mac？我下了后，没用起

是的，我这个分支只支持Windows10+
