### ISSUE TITLE
[功能需求]增加 Windows 下的 Cuda 加速支持

### ISSUE THREAD

**Issue by katana-hydra** [H1DDENADM1N/CapsWriter-Offline#37]
现有的速度已经不算慢了，但是在转写长视频时，速度还是有瓶颈。若是能用 CUDA 加速，相信速度能快十倍。

**Comment by H1DDENADM1N** [comment]
`config.py` 里有一项设置 `provider = "cpu"` ，你可以试下改成 `provider = "gpu"` 管不管用。我电脑不支持cuda，无法帮到你了。
