### ISSUE TITLE
大佬，
那个云剪切板怎么关闭呢，每次一开机就自启了，我完全用不上

### ISSUE THREAD

**Issue by lisidalange** [H1DDENADM1N/CapsWriter-Offline#39]

**Comment by H1DDENADM1N** [comment]
绿色窗口是客户端日志，只有按下
![图片](https://github.com/user-attachments/assets/faf05560-cb84-405f-9090-a7a1fff62070)云朵按钮才是调用了云剪贴板相关功能。如果你不想看到客户端窗口，可以修改`config.py` `class ClientConfig` `shrink_automatically_to_tray = True`
