### ISSUE TITLE
英文单词内部和一连串的数字内部。 都会被空格拆分,该如何解决呢？

### ISSUE THREAD

**Issue by ffgg536956** [H1DDENADM1N/CapsWriter-Offline#43]
当我说英文时， 某些单词上会被空格拆分;  
   当我说数字时，数字之间又存在空格。
如下所示，这个可以解决吗？
H ello,where are  you.
 Be au ti ful  country.

    2 0 2 4 年真不错。

**Comment by H1DDENADM1N** [comment]
服务端日志已有此bug，推测是sensevoice模型问题。我测试了使用funasr模型的老版本是正常的，可继续使用 CapsWriter-Offline-GUI-v1.2.3.7z

**Comment by H1DDENADM1N** [comment]
[Fix #43](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/99cab781b84b22b9156bae0071bcf05fe3b4f129)已修复

将 `util/server_recognize.py`中的
```python
    text = " ".join(result.tokens).replace("@@ ", "")
    text = re.sub("([^a-zA-Z0-9]) (?![a-zA-Z0-9])", r"\1", text)
```
替换为
```python
text = "".join(result.tokens)
```

**Comment by H1DDENADM1N** [comment]
已发布更新修复，欢迎体验：https://github.com/H1DDENADM1N/CapsWriter-Offline/releases
