### ISSUE TITLE
能否增加一个简体/繁体中文的输出呢？

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#45]
`OpenCC`库有这个功能 `(Open Chinese Convert 開放中文轉換)`
 感谢!
![image](https://github.com/user-attachments/assets/37d0e508-22a0-4e34-8bb3-aed0eb3f89fa)

**Comment by H1DDENADM1N** [comment]
好建議，已發佈新版，支持簡繁體轉換：https://github.com/H1DDENADM1N/CapsWriter-Offline/releases

**Comment by JoanthanWu** [comment]
感谢!感谢!
