### ISSUE TITLE
對運用於 `全屏幕遊戲/軟件` 上的設置建議

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#46]
在全屏幕下使用此软件,有可能会失去焦点，从而退出全屏幕.
改变一些设置可以避免:
1. 启用新的`hint_while_recording.exe`
在`hint_while_recording.ini`设置:
 `enableBTT=1`
2. 在`config.py`设置:
`hint_while_recording_at_cursor_position = False` # 是否启用 跟随鼠标光标位置的新版输入状态提示功能
(或者把它改为不争取焦点)

另外补充:
有些游戏并不允许 `Ctrl + V`, 以下设置可模拟键盘的输出, 便可以避免. 至于是否乱碼,那就是后话了.
在`config.py`  设置:
`paste        = False`        # 是否以写入剪切板然后模拟 Ctrl-V 粘贴的方式输出结果

**Comment by H1DDENADM1N** [comment]
请测试[使用hook获取输入光标位置](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/d6eb40ea16534a0150dd617f005cd3c8d6738245)更新后的`hint_while_recording.exe`是否能更准确的获取输入焦点，
[hint_while_recording.zip](https://github.com/user-attachments/files/18048189/hint_while_recording.zip)

**Comment by JoanthanWu** [comment]
> 请测试[使用hook获取输入光标位置](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/d6eb40ea16534a0150dd617f005cd3c8d6738245)更新后的`hint_while_recording.exe`是否能更准确的获取输入焦点， [hint_while_recording.zip](https://github.com/user-attachments/files/18048189/hint_while_recording.zip)

1. `VScode` : 正常
2. `游戏`: 跟之前一样，没有获取到光标,  显示在预定的位置
3. `PyCharm`: 需要切换画面`alt+tab`, 才能获取到坐标-在PyCharm切换之前的`最后光标显示位置`, 至此在没切换至其他画面之前, 都会被判定`最后光标显示位置`.
4. `Listary`: 正常
5. `windows 文件夹`没有光标: 显示在右下角
6. `windows 文件夹`出现光标之后: 正常
7. `edge` 没有光标: 显示在左上角
8. `edge` 出现光标之后: 正常
9. `Obsidian `: 正常

**Comment by H1DDENADM1N** [comment]
参考 https://github.com/abgox/InputTip/issues/61 这似乎又是个难题，像这样黑名单异常的软件如何？

**Comment by JoanthanWu** [comment]
> 参考 [abgox/InputTip#61](https://github.com/abgox/InputTip/issues/61) 这似乎又是个难题，像这样黑名单异常的软件如何？

加入`黑名单`挺好的呀, 可以考虑参考一下哦

**Comment by H1DDENADM1N** [comment]
> 加入`黑名单`挺好的呀, 可以考虑参考一下哦

从[InputTip](https://github.com/abgox/InputTip)抄过来了[获取输入光标位置引入disable_list等](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/00e7d13c57c57c3cf5be819b556ac74e9b4cc821)

**Comment by H1DDENADM1N** [comment]
又做了一些优化，[新增 可通过 hint_while_recording.ini 配置 hintAtCursorPositionList 和 doNotShowHintList](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/aea3d46167df5bbe0f91cf35995bed2e33482dea)

**Comment by JoanthanWu** [comment]
> 又做了一些优化，[新增 可通过 hint_while_recording.ini 配置 hintAtCursorPositionList 和 doNotShowHintList](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/aea3d46167df5bbe0f91cf35995bed2e33482dea)

写的真好, 至今运行得很好.
