### ISSUE TITLE
关于.ahk编译成.exe程序  (hint_while_recording.exe)

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#47]
我发现了一些问题:
在自己的电脑上把`hint_while_recording.ahk`编译成`hint_while_recording.exe`程序,是`不会`被`MicrosoftDefender`当成病毒的.
但是上传到网上之后再下载回来，就`会`被`MicrosoftDefender`当成病毒.

然而在作者@H1DDENADM1N的原来的`hint_while_recording.exe`  这不会被当成病毒，这是为什么呢？
![image](https://github.com/user-attachments/assets/40e6f824-8f5a-4763-9e82-0235769f4593)

**Comment by H1DDENADM1N** [comment]
上传到什么网站？比对下上传前和下载后文件sha-1。如果上传未改变文件sha-1，你可以用 https://sandbox.ti.qianxin.com/sandbox/page 分析检测是否为真病毒，添加MicrosoftDefender排除项，或是改用其他防病毒软件。

**Comment by JoanthanWu** [comment]
经过各种情况的对比,上传前(Github)和`clone`之后的对比, `SHA256` 和 `SHA1`的值都是一样的.
有时候在自己的电脑编译之后(没有上传),也会可能(刚發現)被当成病毒.这就很迷. 
事实上，我不止编译这一个. 还有其他的`.exe`,上传到网上,也会被当成病毒. `.ahk`倒是没被发现过问题.

报告也出来了:
![image](https://github.com/user-attachments/assets/280f7e94-465b-4adb-9867-a769040efe78)

**Comment by JoanthanWu** [comment]
奇怪的是，为什么在1.31或者之前的版本, 由作者你编译的就不会被当成病毒呢?

**Comment by JoanthanWu** [comment]
我还是找个时间重新安AUTOHOTKEY

**Comment by H1DDENADM1N** [comment]
可能某个病毒也用了BeautifulToolTip库，特征被杀软标记了

**Comment by JoanthanWu** [comment]
> 可能某个病毒也用了BeautifulToolTip库，特征被杀软标记了

你是对的, 是否被标记成病毒跟`BeautifulToolTip` 呈高度相关.
我把作者的 1.3.1版本`hint_while_recording.ahk` (没有使用BTT)进行编译, 也没有被侦测到是病毒, 包括使用网站[奇安信情报沙箱](https://sandbox.ti.qianxin.com/sandbox/page)  以及 `MicrosoftDefender` 进行掃描.

如果其他小伙伴看到这里, 没必要担心, 我也使用它.

**Comment by H1DDENADM1N** [comment]
我将误报样本提交给了火绒论坛 https://bbs.huorong.cn/forum.php?mod=viewthread&tid=147249&extra=page%3D1%26filter%3Dlastpost%26orderby%3Dlastpost&fromuid=196113 ，现在火绒安全软件最新病毒库已经不会误报了。使用其他安全软件的伙伴也可以提交误报样本给杀毒软件反馈。

**Comment by JoanthanWu** [comment]
> 我将误报样本提交给了火绒论坛 https://bbs.huorong.cn/forum.php?mod=viewthread&tid=147249&extra=page%3D1%26filter%3Dlastpost%26orderby%3Dlastpost&fromuid=196113 ，现在火绒安全软件最新病毒库已经不会误报了。使用其他安全软件的伙伴也可以提交误报样本给杀毒软件反馈。

哇塞，刚试了`MicrosoftDefender` 也没误报了.
真的没误报了, 厉害了!

**Comment by JoanthanWu** [comment]
至今为止在我这边的`MicrosoftDefender`已经没有误报
