### ISSUE TITLE
希望添加一个可选配置项，只保存文本，类似于是否保存录音文件

### ISSUE THREAD

**Issue by UFDXD** [H1DDENADM1N/CapsWriter-Offline#48]
还是觉的保存录音太大了，只保存文本就好了

**Comment by H1DDENADM1N** [comment]
config.py 中可以设置    `save_audio = True           # 是否保存录音文件`

**Comment by UFDXD** [comment]
@H1DDENADM1N  我将它关闭了，但是它连文本都不保存了。或许它保存但我不知道它保存到那里

**Comment by H1DDENADM1N** [comment]
[原版](https://github.com/HaujetZhao/CapsWriter-Offline/blob/a072f5312031e31706b294e9242d516fb8979fc6/util/client_recv_result.py#L41-L46) save_audio = False 时，会直接不写md记录。

现在将逻辑分开控制。https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/b2260b6700d80ebaff1f134cb6d58d9aece339e1

改动较小，你可以参考
[新增 save_markdown 可选项.zip](https://github.com/user-attachments/files/17987533/save_markdown.zip)
自己改下试试,。

**Comment by UFDXD** [comment]
@H1DDENADM1N  可以的，感谢
