### ISSUE TITLE
启动start_client_gui_admin时，只启动client而不启动service

### ISSUE THREAD

**Issue by QQQOrange** [H1DDENADM1N/CapsWriter-Offline#5]
启动前者的时候，它只启动客户端，不启动相应的服务

**Comment by H1DDENADM1N** [comment]
没看懂你想表达的是什么意思，再详细说说

**Comment by H1DDENADM1N** [comment]
readme.md ✨ 特性

> 18. 一键启动功能：默认服务端 start_server_gui.exe 启动后，自动 🛡️ 以管理员权限 启动客户端 start_client_gui_admin.exe，通过 config.py 中 In_the_meantime_start_the_client 和 In_the_meantime_start_the_client_as_admin 配置

一键启动是服务端唤醒客户端，运行客户端当然不会唤醒服务端啊

**Comment by QQQOrange** [comment]
> readme.md ✨ 特性
> 
> > 18. 一键启动功能：默认服务端 start_server_gui.exe 启动后，自动 🛡️ 以管理员权限 启动客户端 start_client_gui_admin.exe，通过 config.py 中 In_the_meantime_start_the_client 和 In_the_meantime_start_the_client_as_admin 配置
> 
> 一键启动是服务端唤醒客户端，运行客户端当然不会唤醒服务端啊

如果同时启动这个和服务端的话，服务端会提示已经启用了一个

**Comment by H1DDENADM1N** [comment]
> 如果同时启动这个和服务端的话，服务端会提示已经启用了一个

是说开机自启动吗？如果设置了一键启动功能，那么在添加开机启动项的时候，只新建 start_server_gui.exe 的快捷方式就足够了。

**Comment by QQQOrange** [comment]
> > 如果同时启动这个和服务端的话，服务端会提示已经启用了一个
> 
> 是说开机自启动吗？如果设置了一键启动功能，那么在添加开机启动项的时候，只新建 start_server_gui.exe 的快捷方式就足够了。

![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/62794181/3f55cf81-10c6-483c-b36d-5933b34f0a28)
设置是图片这样的，但是开机自己就只起了客户端，没有启动服务的

**Comment by H1DDENADM1N** [comment]
>设置是图片这样的，但是开机自己就只起了客户端，没有启动服务的

不可能啊，客户端是被服务端启动的，如果客户端启动了，那么服务端肯定也启动了呀。

检查下 shell:startup 目录有 start_server_gui.exe 的快捷方式吗？

是不是服务端的托盘图标折叠隐藏了，你误认为服务端没有启动？

用的是最新的 1.1.2 版本吗？

**Comment by QQQOrange** [comment]
> > 设置是图片这样的，但是开机自己就只起了客户端，没有启动服务的
> 
> 不可能啊，客户端是被服务端启动的，如果客户端启动了，那么服务端肯定也启动了呀。
> 
> 检查下 shell:startup 目录有 start_server_gui.exe 的快捷方式吗？
> 
> 是不是服务端的托盘图标折叠隐藏了，你误认为服务端没有启动？
> 
> 用的是最新的 1.1.2 版本吗？

托盘里也没有的 在文件夹里面只放了start_client_gui_admin.exe的快捷方式 版本应该是1.1.1
![image](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/62794181/536d910b-20e7-4049-a692-8e06b33ca81e)

**Comment by H1DDENADM1N** [comment]
> 托盘里也没有的 在文件夹里面只放了start_client_gui_admin.exe的快捷方式 版本应该是1.1.1

更新 1.1.2，删除 start_client_gui_admin.exe ，只放 start_server_gui.exe。保持默认配置，服务端会去自动启动客户端的，不用添加的客户端快捷方式

**Comment by QQQOrange** [comment]
> > 托盘里也没有的 在文件夹里面只放了start_client_gui_admin.exe的快捷方式 版本应该是1.1.1
> 
> 更新 1.1.2，删除 start_client_gui_admin.exe ，只放 start_server_gui.exe。保持默认配置，服务端会去自动启动客户端的，不用添加的客户端快捷方式

是以管理员方式启动吗，老哥

**Comment by H1DDENADM1N** [comment]
> > 更新 1.1.2，删除 start_client_gui_admin.exe ，只放 start_server_gui.exe。保持默认配置，服务端会去自动启动客户端的，不用添加的客户端快捷方式
> 
> 是以管理员方式启动吗，老哥

保持默认设置 In_the_meantime_start_the_client_as_admin = True 是以管理员方式启动

**Comment by QQQOrange** [comment]
> > > 更新 1.1.2，删除 start_client_gui_admin.exe ，只放 start_server_gui.exe。保持默认配置，服务端会去自动启动客户端的，不用添加的客户端快捷方式
> > 
> > 
> > 是以管理员方式启动吗，老哥
> 
> 保持默认设置 In_the_meantime_start_the_client_as_admin = True 是以管理员方式启动

好嘞，谢谢老哥！！！！！！

**Comment by H1DDENADM1N** [comment]
readme.md ❗ 注意事项

> 9.  添加开机自启动的方法：
> 
>     9.1 如果你未更改默认配置（ `In_the_meantime_start_the_client = True` 表示一键启动功能 生效，服务端会自动启动客户端），只用新建 `start_server_gui.exe` 的快捷方式，将服务端的快捷方式放到 `shell:startup` 目录下即可在开机时自动启动服务端和客户端。服务端会自动启动客户端。不要添加客户端的快捷方式。
> 
>     9.1.1 如果你未更改默认配置（ `In_the_meantime_start_the_client_as_admin = True` ），启动服务端会自动以管理员权限启动客户端。
> 
>     9.1.2 如果你更改了默认配置（ `In_the_meantime_start_the_client_as_admin = False` ），启动服务端会自动以用户权限启动客户端。
> 
>     9.2 如果你更改了默认配置（ `In_the_meantime_start_the_client = False` 表示一键启动功能 禁用，启动服务端不会启动客户端），新建 `start_server_gui.exe` 的快捷方式，将服务端的快捷方式放到 `shell:startup` 目录下只会在开机时自动启动服务端。客户端不会被启动。
> 
>     9.3 如果你更改了默认配置（ `In_the_meantime_start_the_client = False` ），新建 `start_client_gui.exe` 的快捷方式，将客户端的快捷方式放到 `shell:startup` 目录下只会在开机时自动启动客户端。服务端不会被启动。不要再添加客户端 `start_client_gui_admin.exe` 的快捷方式。
> 
>     9.4 如果你更改了默认配置（ `In_the_meantime_start_the_client = False` ），新建 `start_client_gui_admin.exe` 的快捷方式，将客户端的快捷方式放到 `shell:startup` 目录下只会在开机时自动以管理员权限启动客户端。服务端不会被启动。不要再添加客户端 `start_client_gui.exe` 的快捷方式。

**Comment by QQQOrange** [comment]
> > 托盘里也没有的 在文件夹里面只放了start_client_gui_admin.exe的快捷方式 版本应该是1.1.1
> 
> 更新 1.1.2，删除 start_client_gui_admin.exe ，只放 start_server_gui.exe。保持默认配置，服务端会去自动启动客户端的，不用添加的客户端快捷方式

好嘞，谢谢老哥
