### ISSUE TITLE
关于单击模式的 1 2 

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#51]
在单击模式下:

1. 使用`CapsLock`开启大小写的功能,在此模式下`未触发`录音模式之前,长按这个按键切换有机率失败，但是进行录音模式`之后`, 成功的几率极大. 当然这个影响不大.
2. 今天才发现`hint_while_recording.exe`这个软件并没有适配单击模式, 可能以后可能会适配一下.
3. 单击模式的雙击功能: 之前的想法是在按下第一次按鍵之后,  录音模式已经触发了, 如果短时间內如果第二次触发此函数就直接把录音模式关闭掉，这样就不符合需要双击功能的想法。因此单击模式的那个`return `还是有点用的.

**Comment by H1DDENADM1N** [comment]
目前结论：
1. `only_enable_microphones_when_pressed_record_shortcut = False` 时单击模式长按大小写切换正常，看代码没看懂影响到哪里造成的这种bug。
2. ahk和py没关联，纯检测按键按下状态，无法检测到是否语音输入中，所以没操作可能性适配单击模式。

**Comment by H1DDENADM1N** [comment]
使用了一段時間，發現双击切换简繁体 bu g 好多呀,比如有時我確實需要輸入一些大寫,然后单击成了繁体，双击反而是简体了好的我都不确定什么时候是简体，什么时候是繁体

**Comment by JoanthanWu** [comment]
> 使用了一段時間，發現双击切换简繁体 bu g 好多呀,比如有時我確實需要輸入一些大寫,然后单击成了繁体，双击反而是简体了好的我都不确定什么时候是简体，什么时候是繁体

根据我之前使用AutoHotKey 写脚本的观察, 得到最后的信息是:
正常情况下, win键盘的特性是  按下后，它会`自动重复`的发出对应键盘的指令:
- 比如说, 按下 `a`键 事实上，他一直会重复发出`a down`的指令,
- 同样的`Capslock`, 也是如此, 那么就有可能你按下但是未抬起来的那段时间`Capslock down`已经发出了指令好几次,
那么解决办法是:
- 每按下键盘，只让它发出指令一次就可, 具体方法如下:
Enabling the FilterKeys Shortcut Key:
1.  In Control Panel, double-click Accessibility Options.
2.  Click the Keyboard tab, click Settings in the FilterKeys section
![image](https://github.com/user-attachments/assets/71435651-5f24-4aa9-85c9-07be78a8908f)

但是他的缺点也是显而易见的:
- 比如说按下删除键，它只会删除一次, 这需要按好几次的删除键.

你可以试试上面的方法.是否有效.

事实上我有类似的困扰就是,`Capslock`会切换中文/英文的输入法, 那么我想到的解决方法是使用AutoHotKey把 `Capslock`改到其他地方, 然后`Capslock原来的按件`则改成其他的影射.(还没修改)

**Comment by JoanthanWu** [comment]
> 使用了一段時間，發現双击切换简繁体 bu g 好多呀,比如有時我確實需要輸入一些大寫,然后单击成了繁体，双击反而是简体了好的我都不确定什么时候是简体，什么时候是繁体

我仔细观察了一下自己的按下键盘情况
看来还是再修改里面的逻辑!

**Comment by JoanthanWu** [comment]
双击功能 bug
按下和弹起第一次:
```
按下
def hold_mode(e: keyboard.KeyboardEvent):
弹起
def hold_mode(e: keyboard.KeyboardEvent):
```
``` 
输出结果:
Cosmic.opposite_state=False
Cosmic.opposite_state=False
```

**一段时间之后** 按下和弹起第二次:
```
按下
def hold_mode(e: keyboard.KeyboardEvent):
弹起
def hold_mode(e: keyboard.KeyboardEvent):
```

```
输出结果:
Cosmic.opposite_state=False
Cosmic.opposite_state=True 
```

结论是:
在第一次弹起之后用来判断`double_clicked`的`时间`并没有重置, 导致最后`double_clicked=True`

**Comment by H1DDENADM1N** [comment]
我懵了，希望你可以修正这些bug，期待你的Pull requests

**Comment by JoanthanWu** [comment]
> 我懵了，希望你可以修正这些bug，期待你的Pull requests

当初看这个`Cosmic.on` 有时间标记的属性就直接用它了
现在弄一个更适合的`last_time_marker` 来代替他.

**Comment by JoanthanWu** [comment]
> 目前结论：
> 
> 1. `only_enable_microphones_when_pressed_record_shortcut = False` 时单击模式长按大小写切换正常，看代码没看懂影响到哪里造成的这种bug。
> 2. ahk和py没关联，纯检测按键按下状态，无法检测到是否语音输入中，所以没操作可能性适配单击模式。

我看了这个`Config.py`的改动, 才知道还有一个bug:
`only_enable_microphones_when_pressed_record_shortcut = False  # 只在按下录音快捷键时启用麦克风
                                                                # 😂注意只在长按模式启用，若hold_mode = False 时将此项True将导致CapsLock按键功能异常`
 我为他写两个是否连接麦克风的逻辑即可.

**Comment by H1DDENADM1N** [comment]
> 我看了这个`Config.py`的改动, 才知道还有一个bug: `only_enable_microphones_when_pressed_record_shortcut = False # 只在按下录音快捷键时启用麦克风 # 😂注意只在长按模式启用，若hold_mode = False 时将此项True将导致CapsLock按键功能异常` 我为他写两个是否连接麦克风的逻辑即可.

好呀好呀，注意先拉取更新[简化配置项](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/21255a849033b19a9f1dbf93ab73423ad4314715)再做更改

**Comment by JoanthanWu** [comment]
现在的版本已经完美解决了上面的问题
