### ISSUE TITLE
关于这个`client_cosmic.py`的全局变量

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#52]
- 感谢大神@H1DDENADM1N, 修正此次的代码改动.
- 我第一次看见那个`client_cosmic.py`说明全局变量的时候，我就去想在这个档案里加一个, 但是发现并没有效, 于是就放弃了这个方法. 或许之后再试一次，看看到底问题出现了在哪里？

**Comment by H1DDENADM1N** [comment]
现在用的就是Cosmic.opposite_state，有遇到什么问题 ・_・?

**Comment by JoanthanWu** [comment]
> 现在用的就是Cosmic.opposite_state，有遇到什么问题 ・_・?

不好意思，我没说清楚: 现在的最新的代碼并没有问题,运行的很好! 我只是回忆起我之前的想法, 为什么会没有生效的问题. 之后我再整理一下思绪再問, 感谢回应!

**Comment by JoanthanWu** [comment]
> * 感谢大神@H1DDENADM1N, 修正此次的代码改动.
> * 我第一次看见那个`client_cosmic.py`说明全局变量的时候，我就去想在这个档案里加一个, 但是发现并没有效, 于是就放弃了这个方法. 或许之后再试一次，看看到底问题出现了在哪里？

嘿嘿, 修正后的代碼比我寫的好看,清晰很多!

**Comment by JoanthanWu** [comment]
> 现在用的就是Cosmic.opposite_state，有遇到什么问题 ・_・?

关于跨模块访问变量值:

为什么我就是读取不到更新后的变量值呢？

我运行以下代码:
```
import keyboard
from client_cosmic import Cosmic

def alt_handler(e: keyboard.KeyboardEvent):
    if e.event_type == keyboard.KEY_UP:
        print(f'我期待看到的是 测试初始量={Cosmic.opposite_state}')
        Cosmic.opposite_state = "我是大聪明"
        print(f'我期待看到的是={Cosmic.opposite_state}')

def bond_shortcut():
    keyboard.hook_key('ctrl', alt_handler, suppress=False)  # 新增一个'简/繁'转换状态的快捷键

if __name__ == "__main__":
    bond_shortcut()
    # 防止脚本立刻退出
    keyboard.wait('esc')
```
得到的输出是:
```
C:\Software\Python\Python3.12\python.exe C:\Software\CapsWriter-Offline-GUI-v1.3.2\util\py传递变量测试G1.py 
第一次运行:
我期待看到的是 测试初始量=测试初始量
我期待看到的是=我是大聪明
第二次运行:
我期待看到的是 测试初始量=我是大聪明
我期待看到的是=我是大聪明
```

最后我从第3个脚本运行，并且读取对应的变量值`Cosmic.opposite_state `:
```
import keyboard
from client_cosmic import Cosmic

def alt_handler(e: keyboard.KeyboardEvent):
    if e.event_type == keyboard.KEY_UP:
        print(f'实际上读到的是={Cosmic.opposite_state}')

def bond_shortcut():
    keyboard.hook_key('alt', alt_handler, suppress=False)  # 新增一个'简/繁'转换状态的快捷键

if __name__ == "__main__":
    bond_shortcut()
    # 防止脚本立刻退出
    keyboard.wait('esc')
```

第3个脚本的输出:
```
C:\Software\Python\Python3.12\python.exe C:\Software\CapsWriter-Offline-GUI-v1.3.2\util\py传递变量测试G2.py 
最终读取:
实际上读到的是=测试初始量
```

**Comment by JoanthanWu** [comment]
这是当时运行的图片:

![读取变量值](https://github.com/user-attachments/assets/804d39a5-e284-479a-9b06-a89a23a611a1)

**Comment by H1DDENADM1N** [comment]
数据变更是内存中操作，不会改变cosmic文件内容，每次重新运行从cosmic读到内存。
你在运行`python.exe py传递变量测试G2.py`和`python.exe py传递变量测试G1.py` 用的不是同一进程，内存中是不一样的
![demo](https://github.com/user-attachments/assets/8d9a3af1-83cd-4140-b828-b0d4de535429)

**Comment by JoanthanWu** [comment]
> 数据变更是内存中操作，不会改变cosmic文件内容，每次重新运行从cosmic读到内存。 你在运行`python.exe py传递变量测试G2.py`和`python.exe py传递变量测试G1.py` 用的不是同一进程，内存中是不一样的 !

感謝! 解说的甚是清晰.
所以我需要去读取那个,更新后代表着`Cosmic.opposite_state变量`的内存中的`值`.
那么问题就来了，我要怎么才能读取到冥冥中的那个内存的值?
我去再看了一遍`client_recv_result.py`中的函数 `async def recv_result():`
思来想去,似乎是跟这句代码有关, 我再仔細的去看看:
```
async def recv_result():
    if not await check_websocket():  #  ←这一句代码
        return
    console.print("[green]连接成功\n")
```

**Comment by JoanthanWu** [comment]
> 数据变更是内存中操作，不会改变cosmic文件内容，每次重新运行从cosmic读到内存。 你在运行`python.exe py传递变量测试G2.py`和`python.exe py传递变量测试G1.py` 用的不是同一进程，内存中是不一样的 !

我又从你的提示中读取到更多信息了:
1. 开启第`4个.py`,
2. 并且把启动热键都放在这`第4个.py`中,
3. 从而使得在启动其他函数的时候, 都被认为是在这`第4个.py` 的进程之中, 那么变量也是属于`第4个.py` 进程.

所以是否是在提示我,`CapsWriter`就是用这个方法来读取`跨模块变量`值呢？

那么在此请教实际上`CapsWriter`是用哪一种方法呢？

- 都放进一个同一个进程中,由`某一个.py`统一启动`其他..py`的函数
- 讀取內存中的值
- 还是其他方法呢？
谢谢谢谢!

**Comment by H1DDENADM1N** [comment]
都放进一个同一个进程中,由某一个.py统一启动其他..py的函数

**Comment by JoanthanWu** [comment]
> 都放进一个同一个进程中,由某一个.py统一启动其他..py的函数

原来如此! 原来如此!
设置的甚世巧妙!
core_client.py:
> init_mic() → asyncio.run(main_mic()) → bond_shortcut()

 感謝@H1DDENADM1N的指導!啊哈哈哈
