### ISSUE TITLE
关于`ComCall`的函数

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#53]
我看见`.ahk`里面有一个`ComCall`函数，不知道大神@H1DDENADM1N 是否记得发出这个消息的`.py`代码在哪里，能否指点一下？我想去拜访一下.

**Comment by H1DDENADM1N** [comment]
.ahk和.py间没有任何交互，纯只检测按键按下

**Comment by JoanthanWu** [comment]
> .ahk和.py间没有任何交互，纯只检测按键按下

居然是这样!? 
行吧, 感谢回应!
