### ISSUE TITLE
是否可以增加一个设置：关闭hint输入提示图标

### ISSUE THREAD

**Issue by NGC13009** [H1DDENADM1N/CapsWriter-Offline#54]
现在在输入的时候会在光标附近弹出黄色的语音输入提示。可以手动在托盘关闭CwH来关闭这个功能。我想在启动的时候就不启动它，有什么办法吗？

因为这个功能有时候会有 bug，具体来说是错位，而且有时候我插拔显示器会导致程序闪退，而且这个功能对于我来说是可以取消掉的，不过目前的设置中，我并没有找到如何在启动的时候默认关闭它

**Comment by H1DDENADM1N** [comment]
注释掉`start_client_gui.py`
```python
    if not check_process("hint_while_recording.exe"):
        subprocess.Popen(
            ["hint_while_recording.exe"], creationflags=subprocess.CREATE_NO_WINDOW
        )
```
如图：
![image](https://github.com/user-attachments/assets/5f9475a4-9a1b-4311-a01e-dcd3030c06dd)

**Comment by H1DDENADM1N** [comment]
更新
[start_client_gui.zip](https://github.com/user-attachments/files/18048023/start_client_gui.zip)
，并将`hint_while_recording.exe`重命名为其他或删除即可。

**Comment by UFDXD** [comment]
我这边也是有时候 错位 和不消失

**Comment by H1DDENADM1N** [comment]
>  我这边也是有时候 错位 和不消失

请更新 https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/aea3d46167df5bbe0f91cf35995bed2e33482dea 可设置部分程序不显示提示或将提示显示在鼠标光标位置 [hint_while_recording.exe](https://github.com/H1DDENADM1N/CapsWriter-Offline/blob/CapsTranser/hint_while_recording.exe)
