### ISSUE TITLE
hot-rule如何设置空格呢

### ISSUE THREAD

**Issue by gaoxuxu110** [H1DDENADM1N/CapsWriter-Offline#57]
我输入": "只输出了冒号, 没有输出冒号+空格

**Comment by H1DDENADM1N** [comment]
hot-rule无法实现加空格，你需要先删除hot-rule中关于冒号的规则，然后修改`util/hot_sub_rule.py`文件：
增加`    句子 = 句子.replace("冒号", "： ")`
如图：
![图片](https://github.com/user-attachments/assets/2418029f-845f-4a7c-b497-90f779180614)
重启客户端后测试
