### ISSUE TITLE
莫名的错误断开了，点了重新启动，但是……反复断连

### ISSUE THREAD

**Issue by UFDXD** [H1DDENADM1N/CapsWriter-Offline#61]

**Comment by UFDXD** [comment]
![2312](https://github.com/user-attachments/assets/0266d5f9-e4bd-432a-af90-0d1137b972e7)

**Comment by H1DDENADM1N** [comment]
重启下服务端

**Comment by H1DDENADM1N** [comment]
已在 https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v2.0.1 修复此问题
