### ISSUE TITLE
可知道进行 静音的时候 不让这个` 通知 `弹出来的方法

### ISSUE THREAD

**Issue by JoanthanWu** [H1DDENADM1N/CapsWriter-Offline#65]
如图:

![image](https://github.com/user-attachments/assets/01a012c7-cf52-4090-a061-f8eb91d72bbb)

**Comment by JoanthanWu** [comment]
1. 他静音的时候显示在左上角
2. Windows 10

**Comment by H1DDENADM1N** [comment]
我搜索到了这个 https://github.com/UnlimitedStack/HideVolumeOSD

http://wordpress.venturi.de/?p=379

以及另一个

https://github.com/irzyxa/Volume2

**Comment by JoanthanWu** [comment]
> 我搜索到了这个 https://github.com/UnlimitedStack/HideVolumeOSD
> 
> http://wordpress.venturi.de/?p=379
> 

我用了这个,成功了! 感谢!
`HideVolumeOSD 1.4`
