### ISSUE TITLE
转录的字幕有问题，PotPlayer播放一段时间后字幕消失

### ISSUE THREAD

**Issue by luceln** [H1DDENADM1N/CapsWriter-Offline#67]
1、生成的字幕在最初的几分钟是可以正常显示的，可是过了大约10分钟后字幕就消失了（时间不一定，有的一个多小时后字幕没了）
2、对比内容，缺失了很多文字，不知道是不是没识别出来
3、短的音频似乎没有问题（测试了多个30分钟以内的音频），长的音频或者视频会有问题（音频是大约2~3小时的直播，视频测试了个48分钟的，31分钟的都有问题）

我提供了B站自带的字幕和软件生成的字幕：
[例子.zip](https://github.com/user-attachments/files/18207221/default.zip)
原视频链接：https://www.bilibili.com/video/BV1aW2NYREFh?spm_id_from=333.788.videopod.episodes&vd_source=f861b73e33952f76ad3364f040c82e2c&p=7

**Comment by H1DDENADM1N** [comment]
Sensevoice模型识别准确度问题，我测试了最后一个使用Paraformer模型的版本[gui-v1.2.3](https://github.com/H1DDENADM1N/CapsWriter-Offline/tree/gui-v1.2.3)字幕是正常的
[登录注册04_by_v123.zip](https://github.com/user-attachments/files/18208094/04_by_v123.zip)


加之[gui-v1.3.1](https://github.com/H1DDENADM1N/CapsWriter-Offline/tree/gui-v1.3.1)就提到过
> ❗此版本不含punc_ct-transformer_cn-en标点符号模型，标点符号由sensevoice模型支持，有时会不加标点。

### 总结

Sensevoice模型虽然多了粤英日韩多语种，但是，中文识别效果大不如Paraformer模型。

我会尽快发布可选模型版本，允许自由选择使用Sensevoice模型还是Paraformer模型。

**Comment by H1DDENADM1N** [comment]
已发布新版 新增 可选项 切换模型 Sensevoice 或 Paraformer https://github.com/H1DDENADM1N/CapsWriter-Offline/releases

**Comment by luceln** [comment]
> 已发布新版 新增 可选项 切换模型 Sensevoice 或 Paraformer https://github.com/H1DDENADM1N/CapsWriter-Offline/releases

好的，现在转录没问题了。
