### ISSUE TITLE
多个长音频批量转录时，处理完第一个音频后闪退

### ISSUE THREAD

**Issue by luceln** [H1DDENADM1N/CapsWriter-Offline#68]
1、多个大约3小时左右的音频拖到客户端进行转录，处理完第一个音频后自动闪退（有几率没有任何处理直接就闪退）
2、多个短音频批量转录没有问题
3、原项目有一个issues，是关于6小时的长音视频闪退的bug，不知道是不是一样的问题，可以的话希望修复一下

**Comment by H1DDENADM1N** [comment]
请发下造成闪退的视频链接。

**Comment by luceln** [comment]
> 请发下造成闪退的视频链接。

这里面的直播回放：https://www.ximalaya.com/album/55183807

**Comment by H1DDENADM1N** [comment]
此问题与 https://github.com/HaujetZhao/CapsWriter-Offline/issues/116 应该是一样的，都是报错 `ConnectionClosedError: no close frame received or sent`



[Fix 转录字幕 大文件 崩溃](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/fcbaa8875c8d6beea1a7d24a604419351f820db3) 
> 异步执行ffmpeg命令：使用asyncio.create_subprocess_exec来替代subprocess.Popen，以避免阻塞事件循环。
> 分块读取数据：避免一次性加载全部数据到内存，特别是在处理大文件时。

已修复，测试六小时音频和两个三小时音频可正常转录，如图：
![图片](https://github.com/user-attachments/assets/0b4e3367-43e2-4a88-8b14-ced6f9db8ea8)

注：
> big.m4a来源：https://www.ximalaya.com/sound/782784357 下载后使用 `.\ffmpeg.exe -i C:\Users\user0\Downloads\test\GKwRIJILLWiZBGeySQM95Q43.m4a -i C:\Users\user0\Downloads\test\GKwRIJILLWiZBGeySQM95Q43copy.m4a -filter_complex concat=n=2:v=0:a=1 -c:a aac C:\Users\user0\Downloads\test\big.m4a` 拼接获得。

下载并替换[/util/client_transcribe.py](https://github.com/H1DDENADM1N/CapsWriter-Offline/blob/CapsTranser/util/client_transcribe.py)测试转录大文件

~缺点~ 特性：转录文件的时候语音输入会被阻塞，要先转录完文件才会继续语音输入

**Comment by luceln** [comment]
> 此问题与 [HaujetZhao#116](https://github.com/HaujetZhao/CapsWriter-Offline/issues/116) 应该是一样的，都是报错 `ConnectionClosedError: no close frame received or sent`
> 
> [Fix 转录字幕 大文件 崩溃](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/fcbaa8875c8d6beea1a7d24a604419351f820db3)
> 
> > 异步执行ffmpeg命令：使用asyncio.create_subprocess_exec来替代subprocess.Popen，以避免阻塞事件循环。
> > 分块读取数据：避免一次性加载全部数据到内存，特别是在处理大文件时。
> 
> 已修复，测试六小时音频和两个三小时音频可正常转录，如图： ![图片](https://private-user-images.githubusercontent.com/65646535/397920123-0b4e3367-43e2-4a88-8b14-ced6f9db8ea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODQzNjQsIm5iZiI6MTczNDc4NDA2NCwicGF0aCI6Ii82NTY0NjUzNS8zOTc5MjAxMjMtMGI0ZTMzNjctNDNlMi00YTg4LThiMTQtY2VkNmY5ZGI4ZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMzU0YzgwOTI0MzE2NjNmMDMwN2ZlNGViNWVlNmJlNTZmMTU1NGQzZWM3MDY1NTVjZGI0ZDU5ZDA4NzEzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4wy-kzy2foXUgBGg0B5kNokpQIQt0WZu3RWp-Gg1LFc)
> 
> 注：
> 
> > big.m4a来源：https://www.ximalaya.com/sound/782784357 下载后使用 `.\ffmpeg.exe -i C:\Users\user0\Downloads\test\GKwRIJILLWiZBGeySQM95Q43.m4a -i C:\Users\user0\Downloads\test\GKwRIJILLWiZBGeySQM95Q43copy.m4a -filter_complex concat=n=2:v=0:a=1 -c:a aac C:\Users\user0\Downloads\test\big.m4a` 拼接获得。
> 
> 下载并替换[/util/client_transcribe.py](https://github.com/H1DDENADM1N/CapsWriter-Offline/blob/CapsTranser/util/client_transcribe.py)测试转录大文件
> 
> ~缺点~ 特性：转录文件的时候语音输入会被阻塞，要先转录完文件才会继续语音输入

转录大文件的问题已经解决，不过测试中发现个小问题，文件名中包含&符号时文件名被截断，导致无法读取到文件。

**Comment by H1DDENADM1N** [comment]
[Fix 文件名中包含&符号时文件名被截断，导致无法读取到文件](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/efae6afd0e7fe0f5c73c2529a11123eb16e03c3a)

下载并替换 [/start_client_gui.py](https://github.com/H1DDENADM1N/CapsWriter-Offline/blob/CapsTranser/start_client_gui.py) 测试转录文件名中包含&符号

**Comment by H1DDENADM1N** [comment]
已打包发布新版 修复 转录字幕四小时大文件崩溃 和 文件名中包含&符号无法读取  https://github.com/H1DDENADM1N/CapsWriter-Offline/releases

**Comment by luceln** [comment]
转录大文件和文件名包含&符号导致文件名截断的问题已修复，关闭issue
