### ISSUE TITLE
关于录制开启的问题

### ISSUE THREAD

**Issue by Lanmaolz** [H1DDENADM1N/CapsWriter-Offline#7]
你这个按大小写录制时关闭视频的功能,使我想切换大小写时会自动开启我正在看视频,请问这个该如何解决？

**Comment by H1DDENADM1N** [comment]
编辑 `config.py` 中的 `mute_other_audio` 和 `pause_other_audio` 可不使用此功能，就不会干预音频播放了

**Comment by H1DDENADM1N** [comment]
请把播放器名称告诉我，我把它加进 excluded_processes 表，你也先可以自己加下。

# 不希望匹配的进程名称列表
    excluded_processes = ['123pan.exe'] # 123pan.exe 启动后始终在播放音频，不知道为什么。影响判断，把它排除掉

**Comment by Lanmaolz** [comment]
就是我浏览器里的视频

**Comment by Lanmaolz** [comment]
还有一个问题，就是我使用你的客户端转录字幕转不出来,视频丢给客户端启动程序没反应

**Comment by H1DDENADM1N** [comment]
> 就是我浏览器里的视频

尝试运行 `.\runtime\python.exe .\util\client_pause_other_audio.py`  ，然后在 EDGE 和 Firefox 暂停播放时语音输入，

结果图：
![MSEDGE](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/5c7da32e-250b-4be6-abeb-e882e1c104ef)


msedge 暂停播放后，仍然告知系统在播放音乐，只在失去窗口活跃状态时告知系统未在播放音乐；这就会导致，在一个网页暂停了播放音乐，但是在网页其他位置语音输入时，造成音频播放暂停被触发。

firefox 暂停播放后，不会告知系统再播放音乐，所以不会有任何问题。

修复方法：
[触发暂停播放排除列表增加EDGE浏览器](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/750089e99572c19aed69148d995719cc717cd756) ，这样对 msedge 就再 在一个网页暂停了播放音乐，但是在网页其他位置语音输入时，就只会静音音频播放，不再触发暂停。

也可以 编辑 `config.py` 中的  `pause_other_audio` 可不使用暂停音频播放功能；编辑 `config.py` 中的  `mute_other_audio` 可不使用静音音频播放功能。

更推荐 使用 Firefox 浏览器

**Comment by H1DDENADM1N** [comment]
> 还有一个问题，就是我使用你的客户端转录字幕转不出来,视频丢给客户端启动程序没反应

bug已修复，请重新下载最新版

**Comment by Lanmaolz** [comment]
我使用的是谷歌浏览器，也和 Edge是一样的吧

**Comment by H1DDENADM1N** [comment]
> 我使用的是谷歌浏览器，也和 Edge是一样的吧

是的，你自己加下排除列表就行
