### ISSUE TITLE
可不可以在开始录音时播放一个音效

### ISSUE THREAD

**Issue by jiemoL** [H1DDENADM1N/CapsWriter-Offline#73]
能不能添加一个功能，在开始录音的时候播放一个提示音。

**Comment by H1DDENADM1N** [comment]
已添加此功能。改动不大暂时不打包7z了，你可以自己改下代码先用着。别忘了把ffplay.exe放项目根目录。

[新增 可选项 开始和结束任务时播放提示音](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/dad82bcd61b95f51d2fcbdf7213f01700bd43229)
> 可在 `config.py` 设置是否启用，以及音频文件路径和音量。需要ffplay.exe
> ffplay.exe 来自 https://www.gyan.dev/ffmpeg/builds/
> start.mp3 和 stop.mp3 音频文件来自 https://pixabay.com
