### ISSUE TITLE
在环境变量里将PYTHONIOENCODING设置为utf-8，程序异常

### ISSUE THREAD

**Issue by ghost** [H1DDENADM1N/CapsWriter-Offline#74]
程序异常表现如下：
- 启动服务端和客户端，提示框内没有任何文字
- 语音识别几次之后客户端就会卡住，必须重启客户端才能再次识别

**Comment by H1DDENADM1N** [comment]
为什么要 `在环境变量里将PYTHONIOENCODING设置为utf-8` ？
最初是想实现什么？
具体做了哪些修改？

**Comment by ghost** [comment]
通过CMD调用一些命令时会出现警告信息，这样设置警告信息不会出现。不过刚刚找到了另一种办法，可以不用为此费神了

**Comment by H1DDENADM1N** [comment]
修改 PYTHONIOENCODING 是 Python2.x 时的做法，在 Python3 极不推荐
