### ISSUE TITLE
UnboundLocalError: cannot accesslocal variable'app'where it is not associated withavalue

### ISSUE THREAD

**Issue by K7Rain** [H1DDENADM1N/CapsWriter-Offline#9]
客户端启动失败
![PixPin_2024-03-06_20-15-14](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/132702046/75c509f1-a5ab-45d0-a272-1fddbcb382a9)

**Comment by H1DDENADM1N** [comment]
以尝试修复，请下载 v1.2.1 测试下。

应该是这里代码错误缩进导致的：

![图片](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/7e3bd24f-ba8d-4a07-991e-9a9baa20ce1b)

**Comment by K7Rain** [comment]
ok了，感谢
